export const GET_WORDS = 'GET_WORDS';
export const SET_WORDS = 'SET_WORDS';
export const GET_WORDS_ERROR = 'GET_WORDS_ERROR';

export const FETCH_DATA = 'FETCH_DATA';
export const UPDATE_DATA = 'UPDATE_DATA';
export const FETCH_DATA_ERROR = 'UPDATE_DATA';

export const GET_WINDOW_SIZE = 'GET_WINDOW_SIZE';
export const GET_ACTIVE_GAMELIST = 'GET_ACTIVE_GAMELIST';
export const GET_ACTIVE_POPUP = 'GET_ACTIVE_POPUP';

export const SIGNIN_TYPE = 'SIGNIN_TYPE';
export const SIGNIN_TYPE_SUCCESS = 'SIGNIN_TYPE_SUCCESS';
export const SIGNIN_TYPE_ERROR = 'SIGNIN_TYPE_ERROR';
export const SET_CURRENT_USER_TOKEN = 'SET_CURRENT_USER_TOKEN';
export const GET_IP_SUCCESS = 'GET_IP_SUCCESS';
export const GET_IP_ERROR = 'GET_IP_ERROR';
export const GET_USERAGENT_SUCCESS = 'GET_USERAGENT_SUCCESS';

export const SIGNOUT_TYPE = 'SIGNOUT_TYPE';
export const SIGNOUT_TYPE_SUCCESS = 'SIGNOUT_TYPE_SUCCESS';
export const SIGNOUT_TYPE_ERROR = 'SIGNOUT_TYPE_ERROR';

export const SIGNUP_TYPE = 'SIGNUP_TYPE';
export const SIGNUP_TYPE_SUCCESS = 'SIGNUP_TYPE_SUCCESS';
export const SIGNUP_TYPE_ERROR = 'SIGNUP_TYPE_ERROR';

export const GET_INFO = 'GET_INFO';
export const SET_INFO = 'SET_INFO';
export const GET_INFO_ERROR = 'GET_INFO_ERROR';

export const CLOSE_GAME = 'CLOSE_GAME';
export const OPEN_GAME = 'OPEN_GAME';
export const SET_OPEN_GAME = 'SET_OPEN_GAME';
export const OPEN_GAME_ERROR = 'OPEN_GAME_ERROR';
export const SET_CLOSE_GAME = 'SET_CLOSE_GAME';
export const CLOSE_GAME_ERROR = 'CLOSE_GAME_ERROR';
export const GET_GAME_HISTORY = 'GET_GAME_HISTORY';
export const SET_GAME_HISTORY = 'SET_GAME_HISTORY';
export const GAME_HISTORY_ERROR = 'GAME_HISTORY_ERROR';

export const GET_PAYMENT = 'GET_PAYMENT';
export const SET_PAYMENT = 'SET_PAYMENT';
export const GET_PAYMENT_ERROR = 'GET_PAYMENT_ERROR';
export const GET_PAYMENT_DEPOSIT = 'GET_PAYMENT_DEPOSIT';
export const SET_PAYMENT_DEPOSIT = 'SET_PAYMENT_DEPOSIT';
export const GET_PAYMENT_ERROR_DEPOSIT = 'GET_PAYMENT_ERROR_DEPOSIT';
export const GET_BALANCE = 'GET_BALANCE';
export const SET_BALANCE = 'SET_BALANCE';
export const GET_BALANCE_ERROR = 'GET_BALANCE_ERROR';

export const ACCOUNT_UPDATE = 'ACCOUNT_UPDATE';
export const ACCOUNT_UPDATE_ERROR = 'ACCOUNT_UPDATE_ERROR';

export const SET_ACTIVE_INPUT = 'SET_ACTIVE_INPUT';

export const SET_ACTIVE_FORM = 'SET_ACTIVE_FORM';


